### ISSUE TITLE
Can BOML be applied in large scaled bilevel programming?

### ISSUE THREAD

**Issue by lijiaqi** [dut-media-lab/BOML#3]
Hi, 
Happy to see your great job! 

I wonder whether BOML could be used for bilevel programming where inner and outer variables are in both large scale, e.g., both are neural network parameters? In my problems, it can be approximately formulated as a Hyperparameters Optimization problem.

**Comment by dut-media-lab** [comment]
With appropriate reformulation, the algorithms in BOML could be used to solve a variety of bilevel optimization problems in different fields. For example, in the classical meta learning problems like few-shot classification problems, we assume the forms of inner variables and outer variables to be flexible enough, so neural network parameters are acceptable.

**Comment by lijiaqi** [comment]
OK. I am really a freshman in bilevel programming(BiP). I wonder whether BiP problems can be solved when inner variables are much more than outer variables... 

I will take a closer look at your BOML and see the possibilities of applications in my problem.
Thank you!
